### ISSUE TITLE
Apply dark mode to [Main] screen ui

### ISSUE THREAD

**Issue by godon019** [dooboolab/whatssub-admin#10]
![current](https://user-images.githubusercontent.com/27461460/61185604-51d92000-a696-11e9-92b7-e127844d0104.png)

Currently dark mode has poor ui. which is not urgent for now but good to improve it later anyway

**Comment by heyman333** [comment]
@godon019 @hyochan  can i take it?

**Comment by heyman333** [comment]
If the `designer` is not in the project, It would be nice to try out the UI framework like https://ant.design/docs/react/introduce

**Comment by godon019** [comment]
> If the `designer` is not in the project, It would be nice to use UI framework like
> [antd](https://ant.design/docs/react/introduce)

that sounds good, but currently our plan is to make 'whatssub-admin' with pure css! (of course with styled component though). so if you are okay with not using any design tools, you can always take it!

**Comment by heyman333** [comment]
@godon019 
Oh, I see! then I'll make this screen look a little nicer!
