### ISSUE TITLE
Implement [ServiceDetail] screen

### ISSUE THREAD

**Issue by hyochan** [dooboolab/whatssub-admin#5]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2410%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/dooboolab/whatssub-admin/issues/5)

![image](https://user-images.githubusercontent.com/27461460/60766870-752a2b00-a0ea-11e9-84f3-bd25e3bcd79c.png)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $10.00)

- [<img src='https://avatars0.githubusercontent.com/u/27461460?v=4' alt='hyochan' width=24 height=24> hyochan](https://issuehunt.io/u/hyochan) ($10.00)
### Submitted pull Requests
- [#11 Feature/service detail screen](https://issuehunt.io/r/dooboolab/whatssub-admin/pull/11)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/dooboolab/whatssub-admin/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by godon019** [comment]
I will take it!
